// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-e0Sa-45NIOitC3C_C256EmjyYuQptQ4',
    appId: '1:806232833396:web:4e52e2721fd43b85e60021',
    messagingSenderId: '806232833396',
    projectId: 'parking-mudde-f14b2',
    authDomain: 'parking-mudde-f14b2.firebaseapp.com',
    storageBucket: 'parking-mudde-f14b2.firebasestorage.app',
    measurementId: 'G-KNNHYWN4Y6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRjCDZmT9XSiGchsWEPCq7zBwTv6-jMZU',
    appId: '1:1015389396822:android:3f5a845ab860f399f140f7',
    messagingSenderId: '1015389396822',
    projectId: 'parking-mudde-adea7',
    storageBucket: 'parking-mudde-adea7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw_p1yOXPHzAjh-CH3quRit1M-tF3BOpg',
    appId: '1:806232833396:ios:b5af457181f28056e60021',
    messagingSenderId: '806232833396',
    projectId: 'parking-mudde-f14b2',
    storageBucket: 'parking-mudde-f14b2.firebasestorage.app',
    iosBundleId: 'com.example.parkingmudde',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw_p1yOXPHzAjh-CH3quRit1M-tF3BOpg',
    appId: '1:806232833396:ios:b5af457181f28056e60021',
    messagingSenderId: '806232833396',
    projectId: 'parking-mudde-f14b2',
    storageBucket: 'parking-mudde-f14b2.firebasestorage.app',
    iosBundleId: 'com.example.parkingmudde',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-e0Sa-45NIOitC3C_C256EmjyYuQptQ4',
    appId: '1:806232833396:web:ec06ed32e7e8c3bce60021',
    messagingSenderId: '806232833396',
    projectId: 'parking-mudde-f14b2',
    authDomain: 'parking-mudde-f14b2.firebaseapp.com',
    storageBucket: 'parking-mudde-f14b2.firebasestorage.app',
    measurementId: 'G-9MJ3GTQX0K',
  );
}
